Repository PhilSoHanse/backend, pull requests merged in 2022-11, with the labels that each got.

#6 OAuth를 이용한 로그인 구현
  noriter/build.gradle
  noriter/src/main/java/com/codewarts/noriter/MemberRepository.java
  noriter/src/main/java/com/codewarts/noriter/NoriterApplication.java
  noriter/src/main/java/com/codewarts/noriter/config/WebConfig.java
  noriter/src/main/java/com/codewarts/noriter/domain/Member.java
  noriter/src/main/java/com/codewarts/noriter/oauth/GithubAccessTokenRequest.java
  noriter/src/main/java/com/codewarts/noriter/oauth/GithubAccessTokenResponse.java
  noriter/src/main/java/com/codewarts/noriter/oauth/GithubOAuthService.java
  noriter/src/main/java/com/codewarts/noriter/oauth/GithubUserInfo.java
  noriter/src/main/java/com/codewarts/noriter/oauth/LoginService.java
  noriter/src/main/java/com/codewarts/noriter/oauth/OAuthAccessToken.java
  noriter/src/main/java/com/codewarts/noriter/oauth/OAuthController.java
  noriter/src/main/java/com/codewarts/noriter/oauth/OAuthProperties.java
  noriter/src/main/java/com/codewarts/noriter/oauth/OAuthPropertiesMapper.java
  noriter/src/main/java/com/codewarts/noriter/oauth/OAuthService.java
  noriter/src/main/java/com/codewarts/noriter/oauth/ResourceServer.java
  noriter/src/main/java/com/codewarts/noriter/oauth/jwt/JwtProperties.java
  noriter/src/main/java/com/codewarts/noriter/oauth/jwt/JwtProvider.java
  noriter/src/main/resources/application.yml
  noriter/src/main/resources/oauth.yml
Labels: ✨ feat, phil, hanse

#7 access token 재발급 기능 구현
  noriter/src/main/java/com/codewarts/noriter/oauth/OAuthController.java
  noriter/src/main/java/com/codewarts/noriter/oauth/jwt/JwtProvider.java
Labels: ✨ feat, phil, hanse

#9 :sparkles: 로그아웃 기능 구현
  noriter/src/main/java/com/codewarts/noriter/domain/Member.java
  noriter/src/main/java/com/codewarts/noriter/oauth/LoginService.java
  noriter/src/main/java/com/codewarts/noriter/oauth/OAuthController.java
Labels: ✨ feat, phil, hanse

#11 커스텀 헤더 상수 선언
  noriter/src/main/java/com/codewarts/noriter/oauth/OAuthAccessToken.java
  noriter/src/main/java/com/codewarts/noriter/oauth/OAuthController.java
  noriter/src/main/java/com/codewarts/noriter/oauth/jwt/JwtProvider.java
  noriter/src/main/java/com/codewarts/noriter/oauth/utils/OAuthUtils.java
Labels: 🥱 chore, phil, hanse

#17 질문 게시판 등록 기능 구현
  noriter/build.gradle
  noriter/src/main/java/com/codewarts/noriter/article/controller/QuestionController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Article.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Hashtag.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Question.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/question/QuestionPostRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/exception/member/NoSuchMemberException.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
  noriter/src/test/java/com/codewarts/noriter/article/service/QuestionServiceTest.java
  noriter/src/test/resources/application.yml
  noriter/src/test/resources/oauth.yml
Labels: ✨ feat, phil

#18 스터디 게시판 글 등록하기 기능 구현
  noriter/build.gradle
  noriter/src/main/java/com/codewarts/noriter/article/controller/QuestionController.java
  noriter/src/main/java/com/codewarts/noriter/article/controller/StudyController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Article.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Hashtag.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Question.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Study.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/study/StudyPostRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/service/StudyService.java
  noriter/src/main/resources/data.sql
  noriter/src/test/java/com/codewarts/noriter/article/service/QuestionServiceTest.java
  noriter/src/test/java/com/codewarts/noriter/article/service/StudyServiceTest.java
  noriter/src/test/resources/application.yml
  noriter/src/test/resources/oauth.yml
Labels: ✨ feat, hanse

#22 스터디 게시판 리스트 조회 기능 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/StudyController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Study.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/study/StudyListResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/service/StudyService.java
  noriter/src/main/resources/application.yml
  noriter/src/main/resources/data.sql
Labels: ✨ feat, hanse

#23 질문 게시판 리스트 조회 기능 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/QuestionController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Article.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Question.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/question/QuestionResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
  noriter/src/test/java/com/codewarts/noriter/article/controller/QuestionControllerTest.java
  noriter/src/test/java/com/codewarts/noriter/article/service/QuestionServiceTest.java
  noriter/src/test/resources/application.yml
Labels: ✨ feat, phil

#27 질문 게시판 상세 조회 기능 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/QuestionController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Article.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/question/QuestionDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/exception/member/NoSuchMemberException.java
  noriter/src/main/java/com/codewarts/noriter/article/exception/question/NoSuchQuestionException.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
  noriter/src/main/java/com/codewarts/noriter/comment/domain/dto/CommentResponse.java
  noriter/src/main/java/com/codewarts/noriter/common/domain/dto/WriterInfoResponse.java
Labels: ✨ feat, phil

#31 질문 게시판 글 삭제 기능 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/QuestionController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Article.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
Labels: ✨ feat, phil

#32 스터디 글 삭제하기 기능 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/StudyController.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
  noriter/src/main/java/com/codewarts/noriter/article/service/StudyService.java
Labels: ✨ feat, hanse

#33 테스트 환경 설정 및 패키지 구조 변경
  noriter/src/main/resources/application-dev.yml
  noriter/src/main/resources/application.yml
  noriter/src/test/java/com/codewarts/noriter/article/controller/QuestionControllerTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/question/QuestionCreateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/study/StudyCreateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/service/QuestionServiceTest.java
  noriter/src/test/java/com/codewarts/noriter/article/service/StudyServiceTest.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/StudyServiceTest.java
  noriter/src/test/resources/application-test.yml
  noriter/src/test/resources/application.yml
  noriter/src/test/resources/data.sql
  noriter/src/test/resources/oauth.yml
Labels: 📑 docs, ✨ feat, phil, hanse

#35 파일명 변경 및 패키지변경
  noriter/src/test/java/com/codewarts/noriter/article/docs/study/StudyCreateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/QuestionServiceTest.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/StudyServiceTest.java
Labels: 🥱 chore, phil, hanse

#38 스터디 게시판 해결여부 편집 기능 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/StudyController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Study.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/service/StudyService.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/study/StudyUpdateCompletionTest.java
Labels: ✨ feat, hanse

#40 질문 게시판 수정 기능 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/QuestionController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Article.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/Question.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/question/QuestionUpdateRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/exception/member/NoSuchMemberException.java
  noriter/src/main/java/com/codewarts/noriter/article/exception/question/NoSuchQuestionException.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/question/QuestionCreateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/QuestionServiceTest.java
  noriter/src/test/resources/data.sql
Labels: ✨ feat, phil

#47 자유게시글 상세조회 기능 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/FreeController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/free/FreeDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/service/FreeService.java
  noriter/src/main/java/com/codewarts/noriter/common/domain/dto/WriterInfoResponse.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/free/FreeDetailTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/study/StudyDetailTest.java
  noriter/src/test/resources/data.sql
Labels: ✨ feat, hanse

#51 자유게시글 편집 기능 조회 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/FreeController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/free/FreeEditRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/service/FreeService.java
Labels: ✨ feat, hanse
