Repository PhilSoHanse/backend, pull requests merged in 2023-02, with the labels that each got.

#80 배포 테스트용 PR
  .github/workflows/gradle.yml
  noriter/.gitignore
  noriter/Dockerfile
  noriter/appspec.yml
  noriter/build.gradle
  noriter/gradle/wrapper/gradle-wrapper.jar
  noriter/scripts/deploy.sh
  noriter/src/main/resources/application-deploy.yml
  noriter/src/main/resources/application.yml
Labels: ✨ feat

#81 배포 workflows 내용 수정
  .github/workflows/gradle.yml
  noriter/src/main/resources/application-deploy.yml
  noriter/src/main/resources/application.yml
  noriter/src/main/resources/oauth.yml
Labels: phil, hanse, 🔧 fix

#83 찜 등록 기능 및 테스트 구현
  noriter/src/main/java/com/codewarts/noriter/common/config/WebConfig.java
  noriter/src/main/java/com/codewarts/noriter/exception/type/WishExceptionType.java
  noriter/src/main/java/com/codewarts/noriter/wish/controller/WishController.java
  noriter/src/main/java/com/codewarts/noriter/wish/domain/Wish.java
  noriter/src/main/java/com/codewarts/noriter/wish/repository/WishRepository.java
  noriter/src/main/java/com/codewarts/noriter/wish/service/WishService.java
  noriter/src/main/resources/application.yml
  noriter/src/test/java/com/codewarts/noriter/article/docs/wish/WishCreateTest.java
  noriter/src/test/resources/data.sql
Labels: ✨ feat, phil, hanse

#85 찜 취소 기능 구현
  noriter/src/main/java/com/codewarts/noriter/exception/type/WishExceptionType.java
  noriter/src/main/java/com/codewarts/noriter/wish/controller/WishController.java
  noriter/src/main/java/com/codewarts/noriter/wish/repository/WishRepository.java
  noriter/src/main/java/com/codewarts/noriter/wish/service/WishService.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/wish/WishDeleteTest.java
Labels: ✨ feat, phil, hanse

#87 자유게시판 조회 시 찜 여부 확인기능 추가
  noriter/src/main/java/com/codewarts/noriter/article/controller/FreeController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/free/FreeDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/free/FreeListResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/service/FreeService.java
  noriter/src/main/java/com/codewarts/noriter/interceptor/AuthVerificationInterceptor.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/free/FreeDetailTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/free/FreeListTest.java
  noriter/src/test/resources/data.sql
Labels: ✨ feat, phil, hanse

#89 질문게시판 조회 시 찜 여부 확인 기능 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/QuestionController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/question/QuestionDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/question/QuestionListResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/question/QuestionDetailTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/question/QuestionListTest.java
  noriter/src/test/resources/data.sql
Labels: ✨ feat, phil

#91 질문게시판 조회 시 찜 여부 확인 기능 및 테스트 구현
  noriter/src/main/java/com/codewarts/noriter/article/controller/StudyController.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/study/StudyDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/domain/dto/study/StudyListResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/service/FreeService.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
  noriter/src/main/java/com/codewarts/noriter/article/service/StudyService.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/study/StudyDetailTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/study/StudyListTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/wish/WishCreateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/wish/WishDeleteTest.java
  noriter/src/test/resources/data.sql
Labels: ✨ feat, hanse

#93 패키지 정리
  noriter/src/main/java/com/codewarts/noriter/article/controller/FreeController.java
  noriter/src/main/java/com/codewarts/noriter/article/controller/QuestionController.java
  noriter/src/main/java/com/codewarts/noriter/article/controller/StudyController.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/free/FreeDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/free/FreeEditRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/free/FreeListResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/free/FreePostRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/question/QuestionDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/question/QuestionListResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/question/QuestionPostRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/question/QuestionUpdateRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/study/StudyDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/study/StudyEditRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/study/StudyListResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/study/StudyPostRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/QuestionRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/StudyRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/service/FreeService.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
  noriter/src/main/java/com/codewarts/noriter/article/service/StudyService.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/CommentResponse.java
  noriter/src/main/java/com/codewarts/noriter/member/dto/WriterInfoResponse.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/question/QuestionEditTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/question/QuestionUpdateStatusTest.java
Labels: 🔧 fix

#95 :sparkles: 대댓글 엔티티 생성 및 댓글과의 연관관계 맵핑
  noriter/src/main/java/com/codewarts/noriter/comment/domain/Comment.java
  noriter/src/main/java/com/codewarts/noriter/comment/domain/ReComment.java
Labels: ✨ feat, phil, hanse

#98 대댓글 등록 기능 및 테스트 구현
  noriter/src/main/java/com/codewarts/noriter/comment/controller/CommentController.java
  noriter/src/main/java/com/codewarts/noriter/comment/domain/ReComment.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/recomment/ReCommentRequest.java
  noriter/src/main/java/com/codewarts/noriter/comment/repository/CommentRepository.java
  noriter/src/main/java/com/codewarts/noriter/comment/repository/ReCommentRepository.java
  noriter/src/main/java/com/codewarts/noriter/comment/service/CommentService.java
  noriter/src/main/java/com/codewarts/noriter/common/config/WebConfig.java
  noriter/src/main/java/com/codewarts/noriter/exception/type/CommentExceptionType.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/free/FreeListTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/recomment/ReCommentCreateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/study/StudyDeleteTest.java
  noriter/src/test/resources/data.sql
Labels: ✨ feat, hanse

#100 댓글 등록 기능 구현
  noriter/src/main/java/com/codewarts/noriter/article/dto/free/FreeDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/question/QuestionDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/study/StudyDetailResponse.java
  noriter/src/main/java/com/codewarts/noriter/comment/controller/CommentController.java
  noriter/src/main/java/com/codewarts/noriter/comment/domain/Comment.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/comment/CommentPostRequest.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/comment/CommentResponse.java
  noriter/src/main/java/com/codewarts/noriter/comment/service/CommentService.java
  noriter/src/main/java/com/codewarts/noriter/common/config/WebConfig.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/comment/CommentCreateTest.java
Labels: ✨ feat, phil

#102 댓글 수정 기능 구현 PR 보냅니다.
  noriter/src/main/java/com/codewarts/noriter/comment/controller/CommentController.java
  noriter/src/main/java/com/codewarts/noriter/comment/domain/Comment.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/comment/CommentUpdateRequest.java
  noriter/src/main/java/com/codewarts/noriter/comment/service/CommentService.java
  noriter/src/main/java/com/codewarts/noriter/common/config/WebConfig.java
  noriter/src/main/java/com/codewarts/noriter/exception/type/CommentExceptionType.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/comment/CommentEditTest.java
  noriter/src/test/resources/data.sql
Labels: ✨ feat

#106 댓글 삭제 기능 구현 및 테스트
  noriter/src/main/java/com/codewarts/noriter/comment/controller/CommentController.java
  noriter/src/main/java/com/codewarts/noriter/comment/domain/Comment.java
  noriter/src/main/java/com/codewarts/noriter/comment/service/CommentService.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/comment/CommentDeleteTest.java
Labels: ✨ feat

#107 대댓글 삭제 기능 및 테스트 구현
  noriter/src/main/java/com/codewarts/noriter/comment/controller/CommentController.java
  noriter/src/main/java/com/codewarts/noriter/comment/domain/ReComment.java
  noriter/src/main/java/com/codewarts/noriter/comment/service/CommentService.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/recomment/ReCommentDeleteTest.java
Labels: ✨ feat, hanse

#109 대댓글 조회 기능 구현 및 게시글 소프트 딜리트로 수정
  noriter/src/main/java/com/codewarts/noriter/article/domain/Article.java
  noriter/src/main/java/com/codewarts/noriter/article/service/FreeService.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
  noriter/src/main/java/com/codewarts/noriter/article/service/StudyService.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/comment/CommentResponse.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/recomment/RecommentResponse.java
  noriter/src/main/resources/application-dev.yml
  noriter/src/main/resources/application.yml
  noriter/src/test/java/com/codewarts/noriter/article/docs/free/FreeDeleteTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/free/FreeDetailTest.java
  noriter/src/test/resources/data.sql
Labels: ✨ feat, phil, hanse, ⚒ refactor
