Repository PhilSoHanse/backend, pull requests merged in 2023-03, with the labels that each got.

#113 자유게시판 서비스 단위 테스트 구현
  noriter/src/main/java/com/codewarts/noriter/article/dto/playground/PlaygroundCreateRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/playground/PlaygroundUpdateRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/PlaygroundServiceTest.java
Labels: ✨ feat, phil, hanse

#115 코드 리팩토링
  noriter/src/main/java/com/codewarts/noriter/article/domain/Article.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/ArticleRepository.java
  noriter/src/main/java/com/codewarts/noriter/article/repository/CustomArticleRepositoryImpl.java
  noriter/src/main/java/com/codewarts/noriter/article/service/GatheringService.java
  noriter/src/main/java/com/codewarts/noriter/article/service/PlaygroundService.java
  noriter/src/main/java/com/codewarts/noriter/article/service/QuestionService.java
  noriter/src/main/java/com/codewarts/noriter/comment/controller/CommentController.java
  noriter/src/main/java/com/codewarts/noriter/comment/domain/Comment.java
  noriter/src/main/java/com/codewarts/noriter/comment/domain/ReComment.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/comment/CommentCreateRequest.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/comment/CommentResponse.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/recomment/ReCommentCreateRequest.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/recomment/ReCommentUpdateRequest.java
  noriter/src/main/java/com/codewarts/noriter/comment/dto/recomment/RecommentResponse.java
  noriter/src/main/java/com/codewarts/noriter/comment/repository/ReCommentRepository.java
  noriter/src/main/java/com/codewarts/noriter/comment/service/CommentService.java
  noriter/src/main/java/com/codewarts/noriter/exception/type/CommentExceptionType.java
  noriter/src/main/java/com/codewarts/noriter/exception/type/ReCommentExceptionType.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/comment/CommentDeleteTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/comment/CommentUpdateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/comment/ReCommentCreateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/gathering/GatheringDetailTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/gathering/GatheringListTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/gathering/GatheringUpdateStatusTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/gathering/GatheringUpdateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/playground/PlaygroundDetailTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/playground/PlaygroundListTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/playground/PlaygroundUpdateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/question/QuestionDeleteTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/question/QuestionUpdateStatusTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/question/QuestionUpdateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/recomment/ReCommentDeleteTest.java
  noriter/src/test/java/com/codewarts/noriter/article/docs/recomment/ReCommentUpdateTest.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/PlaygroundServiceTest.java
  noriter/src/test/resources/application-unit.yml
  noriter/src/test/resources/data.sql
Labels: ✨ feat, phil, hanse, ⚒ refactor

#118 QuestionService 테스트 구현
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/PlaygroundServiceTest.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/QuestionServiceTest.java
Labels: phil

#119 GatheringService 테스트 구현
  noriter/src/main/java/com/codewarts/noriter/article/dto/gathering/GatheringCreateRequest.java
  noriter/src/main/java/com/codewarts/noriter/article/dto/gathering/GatheringUpdateRequest.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/GatheringServiceTest.java
Labels: ✨ feat, hanse

#123 CI 적용 및 application.yml 수정
  .github/workflows/build.yml
  noriter/build.gradle
  noriter/src/test/java/com/codewarts/noriter/article/docs/InitIntegrationRestDocsTest.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/GatheringServiceTest.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/PlaygroundServiceTest.java
  noriter/src/test/java/com/codewarts/noriter/article/unit/service/QuestionServiceTest.java
  noriter/src/test/resources/application-test.yml
  noriter/src/test/resources/application-unit.yml
Labels: ✨ feat, phil, hanse
